//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdditionalSubject
    {
        public int ID { get; set; }
        public int Key { get; set; }
        public int Seq { get; set; }
    
        public virtual Detail Detail { get; set; }
        public virtual SubjectTable SubjectTable { get; set; }
    }
}
