//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashboardQuestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DashboardQuestion()
        {
            this.DashboardAnswers = new HashSet<DashboardAnswer>();
        }
    
        public int QID { get; set; }
        public string Question { get; set; }
        public System.DateTime Datetime { get; set; }
        public string ID { get; set; }
        public Nullable<int> Number { get; set; }
        public string CollegeName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DashboardAnswer> DashboardAnswers { get; set; }
    }
}
