//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Detail()
        {
            this.AdditionalSubjects = new HashSet<AdditionalSubject>();
            this.LibraryTables = new HashSet<LibraryTable>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string College { get; set; }
        public string Branch { get; set; }
        public string Year { get; set; }
        public string MobileNo { get; set; }
        public string Image { get; set; }
        public string Password { get; set; }
        public string AuthCode { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdditionalSubject> AdditionalSubjects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LibraryTable> LibraryTables { get; set; }
    }
}
