//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CollegeBuddyEntities : DbContext
    {
        public CollegeBuddyEntities()
            : base("name=CollegeBuddyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Detail> Details { get; set; }
        public virtual DbSet<DashboardAnswer> DashboardAnswers { get; set; }
        public virtual DbSet<DashboardQuestion> DashboardQuestions { get; set; }
        public virtual DbSet<AdditionalSubject> AdditionalSubjects { get; set; }
        public virtual DbSet<BranchTable> BranchTables { get; set; }
        public virtual DbSet<CommentTable> CommentTables { get; set; }
        public virtual DbSet<LibraryTable> LibraryTables { get; set; }
        public virtual DbSet<PDFDetail> PDFDetails { get; set; }
        public virtual DbSet<PDFTable> PDFTables { get; set; }
        public virtual DbSet<SubjectTable> SubjectTables { get; set; }
    }
}
