//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDFDetail
    {
        public int PKey { get; set; }
        public string Review { get; set; }
        public int Rating { get; set; }
        public int Downloads { get; set; }
        public int User { get; set; }
        public int Primarykey { get; set; }
    
        public virtual PDFTable PDFTable { get; set; }
    }
}
